### PR TITLE
2017 state legislative geojson files from census.gov

### PR DESCRIPTION
**Pull request by cormander**
Hi,

Love your repo! I needed state legislative shapefiles too, and I saw the "Shapes for state legislative districts" in the TODO. So here's the PR for it. Using https://www.npmjs.com/package/shapefile with https://github.com/openstates/openstates-district-maps I was able to create the geojson files for each district in each state. Please give this a look and let me know if I need to change anything and resubmit. Thanks,

### CODE REVIEW

**Comment by konklone** [comment]
@cormander This is an amazing contribution! I'm going through an email/GitHub backlog and my apologies for letting this sit. I won't be able to review it today, but I can do that ASAP this week.

Since the diff is too big to examine in-web, would you mind putting the URL/directory pattern you're proposing, as well as any other relevant choices you made, into a comment here for the record?

**Comment by cormander** [comment]
Thanks :) No problem on the wait.

There are a total of 6,744 geojson files added with this commit. The directory structure is as follows:

states/\<state\>/\<type\>/\<district number\>.geojson

So, looking at California State Assembly district 47, it would be:

    states/CA/sldl/47.geojson

Basically, I put the files in the same directory as the states, so when you do a directory listing of the state, you see:

    shape.geojson
    sldl/
    sldu/

The `sldl` and `sldu` types are used by census.gov as well as the Open Civic Data Division Identifiers (OCDID) and stand for "State Legislative District" - and either "lower" or "upper" - lower is usually named House (but is "Assembly" or others in a few states) and upper is almost always senate. Nebraska (NE) is the only state that has a single legislative body - so there's no `sldl` type for that one.

I chose to put them in the already existing state directory, and not a seperate directory like the congressional districts ("cds"), because they're specific to each state, while congress is specific to the US federal government. 

These files were generated by the `shapefiles` command mentioned above to convert the KML files to geojson. It's a few hundred megabytes of data so I opted to leave out the source KML files to save space. This is also why I opted to not put the year in them, as storing history as seperate files could get out of hand real fast.

Some of the US territories that have legislative districts such as American Samoa and Puerto Rico aren't in this data set because the source maps I used omitted them - eventually I'll follow up and add those in as well. What I really need to do is write automation that runs every week and notifies me of changes, and then I can add those extra territories. If you're interested in storing those scripts in this repo, or another one, let me know.

Oh and, for what it's worth, here's a 48 second video describing how I'm using this data in our open source free canvassing mobile app: https://www.youtube.com/watch?v=4lf56_-GfqY

Geofencing so people don't wander outside the intended area :)

Thanks,

**Comment by cormander** [comment]
Hey @konklone - any feedback here? Thanks,

**Comment by konklone** [comment]
Let's go with it and see how it goes!

**Pull request merged**
