### PR TITLE
Added NJ 2022 districts

### LINKED ISSUE #30: Update NJ congressional districts for 2022
New districts were adopted Dec 22, 2021 and available here: https://www.njredistrictingcommission.org/adoption2022map.asp

I have some time to make this PR later this week if someone does not get to it first.

### PR DESCRIPTION
**Pull request by nickoneill**
Fixes #30, data from https://www.njredistrictingcommission.org/adoption2022map.asp

### CODE REVIEW

**Comment by nickoneill** [comment]
Are y'all interested in this @JoshData @dwillis? I'll be doing the rest of the states as well, I would like to contribute them here as well if you want to stay up to date.

**Comment by dwillis** [comment]
@nickoneill Hey Nick, yes, thanks! Sorry for the delay in responding, but we'd love to have the rest of the states too.

**Comment by nickoneill** [comment]
Sounds good! I will start adding more states in PRs as I gather the data... and I'll make a top level issue to track what's done. There's a lot that is undecided still, and some "final" maps that are in litigation as well.

**Comment by JoshData** [comment]
Thanks for the heads up. I use the Census shapefiles directly when updating our maps at the start of each new Congress, so I've got 10 months before I need to think about this. :)

**Pull request merged**
