### PR TITLE
add 2018 PA districts

### LINKED ISSUE #11: Support new PA districts
PA has new districts!

There are GeoJSON files here (https://github.com/R35I5T/dev/blob/master/PA.geojson) which come from the state website (http://www.pacourts.us/news-and-statistics/cases-of-public-interest/league-of-women-voters-et-al-v-the-commonwealth-of-pennsylvania-et-al-159-mm-2017?66). They look right to me.

I'll attempt format them and make a PR later today

### PR DESCRIPTION
**Pull request by MetricMike**
Fixes #11 and adds KML files too.

I opted to only create a PA folder, since [Readme#Using-The-Shapes](https://github.com/unitedstates/districts#using-the-shapes) says the year indicates when the maps came into effect, and AFAIK all other states are using the 2016 maps.

### CODE REVIEW

**Comment by MetricMike** [comment]
[Gist](https://gist.github.com/MetricMike/a9db14cdd2d636679d4dfe06c950c9c8) with the steps I used to make these, for the next state that gets redistricted

**Comment by ben-pr-p** [comment]
oh hey! duplicated efforts (#13). I should've checked before I did this.

Yours is better!

**Comment by dwillis** [comment]
This looks good to me.

**Comment by MetricMike** [comment]
Hey! Just checking in on the status of this. I rely pretty heavily on this repo, and if there's additional code/files/justifications I can provide in future PRs to speed them along, just let me know!

**Pull request merged**
